const Sequelize = require("sequelize")
const sequelize = require('../util/database')

const dishout = sequelize.define('dishOut_processOrder',{
    id:{
        type:Sequelize.INTEGER,
        autoIncrement:true,
        allowNull:false,
        primaryKey:true
    },
    amount:
    {
        type:Sequelize.STRING,
        allowNull:false
    },
    authNumber:{
        type:Sequelize.STRING,
        allowNull:false
    },
    autoPower:{
        type:Sequelize.STRING,
        allowNull:false
    },
    city:{
        type:Sequelize.STRING,
        allowNull:false
    },
    customerId:{
        type:Sequelize.STRING,
        allowNull:false
    },
    customerName:{
        type:Sequelize.STRING,
        allowNull:false
    },
    callBackUrl:{
        type:Sequelize.STRING,
        allowNull:false
    },
    DeviceIds:{
        type:Sequelize.STRING,
        allowNull:false
    },
    Email:{
        type:Sequelize.STRING,
        allowNull:false
    },
    forceBatch:{
        type:Sequelize.STRING,
        allowNull:false
    },
    latitude:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    longtitude:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    InvoiceNumber:{
        type:Sequelize.STRING,
        allowNull:false
    },
    itemId:{
        type:Sequelize.STRING,
        allowNull:false
    },
    itemName:{
        type:Sequelize.STRING,
        allowNull:false
    },
    itemPrice:{
        type:Sequelize.STRING,
        allowNull:false
    },
    quantity:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    merchantId:{
        type:Sequelize.STRING,
        allowNull:false
    },
    module:{
        type:Sequelize.STRING,
        allowNull:false
    },
    OrderDate:{
        type:Sequelize.STRING,
        allowNull:false
    },
    OriginatorId:{
        type:Sequelize.STRING,
        allowNull:false
    },
    PNREF:{
        type:Sequelize.STRING,
        allowNull:false
    },
    processorToken:{
        type:Sequelize.STRING,
        allowNull:false
    },
    register:{
        type:Sequelize.STRING,
        allowNull:false
    },
    requestBatch:{
        type:Sequelize.STRING,
        allowNull:false
    },
    SKU:{
        type:Sequelize.STRING,
        allowNull:false
    },
    SSID:{
        type:Sequelize.INTEGER,
        allowNull:false
    },
    state:{
        type:Sequelize.STRING,
        allowNull:false
    },
    status:{
       type:Sequelize.STRING,
       allowNull:false
    },
    streetAddress:{
        type:Sequelize.STRING,
        allowNull:false
    },
    transactionType:{
        type:Sequelize.STRING,
        allowNull:false
    },
    zip:{
        type:Sequelize.STRING,
        allowNull:false
    }  
})


module.exports=dishout